### ISSUE TITLE
Dialogs with % are misreading the input

### ISSUE THREAD

**Issue by AaronDavidNewman** [Smoosic/Smoosic#17]
I'm not sure what changed, but for instance, for global layout, the scale should be a percentage, 55 === 55%.  Somehow 55 is being read As 0.55 %.

**Comment by strangarnenad** [comment]
@AaronDavidNewman changes I made on a rocker component when I was adding min and max values caused this behaviour.
This pr should fix it https://github.com/Smoosic/Smoosic/pull/18

**Comment by AaronDavidNewman** [comment]
Oh, this was fixed with the PR, closing
