### ISSUE TITLE
Selected note does not play when pressing RightArrow

### ISSUE THREAD

**Issue by danjferg** [Smoosic/Smoosic#20]
I hear the note play when I use LeftArrow and mouse, but not on RightArrow. SUI tracker has a required parameter on whether to skip the note, and it always evaluates true because application eventHandler.ts evKey always sends the view score.

This is not an issue with tracker growSelectionRight because evenHandler goes to the parameterless function which then forwards to _growSelectionRight defaulting to false.

**Comment by AaronDavidNewman** [comment]
Thanks for looking into this, I noticed something was odd with the playback.  Do you have an interest in submitting a PR?  It seems like you already have a grasp on what is going on.

**Comment by danjferg** [comment]
I don't know the code well enough to submit a good commit that will cover all other methods that call this function. I just know enough to debug and find root cause. If I decide to dive in deeper for personal project usage then I will take you up on that later.

**Comment by AaronDavidNewman** [comment]
OK, well I appreciate the report.  We will look at this shortly.

**Comment by AaronDavidNewman** [comment]
Fixed with PR #23
